import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "./ui/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='flex'>
        <Sidebar />
        <main className='flex-1 p-4 ml-64'>
          {" "}
          {/* Add ml-64 to account for the sidebar width */}
          {children}
        </main>
      </body>
    </html>
  );
}
