import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./ui/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className="flex flex-col items-center justify-center m-0">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
